apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      color: blue
  template:
    metadata:
      labels:
        app: myapp
        color: blue
    spec:
      containers:
      - name: myapp
        image: hanishrishen/myapp:1
        ports:
        - containerPort: 8080
        env:
        - name: VERSION
          value: "blue-v1"
